development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twitter_like_app_development
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twitter_like_app_test
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twitter_like_app_production
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock
